-- Auto-generated from prototype data. Regenerate via scratchpad/gen-seed.mjs. Do not edit by hand.

-- media assets
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png', 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png', 'image/png', 'image');
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_jik0zpjik0zpjik0.png', 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png', 'image/png', 'image');
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_udj4nuudj4nuudj4.png', 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png', 'image/png', 'image');
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_wo6oltwo6oltwo6o.png', 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png', 'image/png', 'image');
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_mlj41hmlj41hmlj4.png', 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png', 'image/png', 'image');
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png', 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png', 'image/png', 'image');
insert into media_asset (filename, url, mime, kind) values ('Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png', 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png', 'image/png', 'image');

-- shows, hosts, episodes
insert into show (slug, name, tagline, blurb, description, schedule_slot, episodes_count, hours_per_week, monthly_views, cover_media_id, sort, published) values ('the-opening-bell', 'The Opening Bell', 'DAILY · WEEKDAYS 09:30 ET', 'Two hours on the tape as it prints, from the bell.', 'Two hours on the tape as it prints. Order flow, breadth, and the trades desks are actually putting on — before the narrative catches up.', 'WEEKDAYS 09:30 ET', 1412, '10 hrs', '4.2M', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), 0, true);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='the-opening-bell'), 'DW', 'Dana Whitfield', 'Anchor · 14 years on an equities desk', 0);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='the-opening-bell'), 'MO', 'Marcus Oyelaran', 'Markets editor · former futures broker', 1);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='the-opening-bell'), 'RA', 'Renee Ash', 'Options contributor', 2);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-opening-bell'), 'chips-lead-a-narrow-tape-as-breadth-thins-into-the-fed-window', 'EP 1,412', 'Chips lead a narrow tape as breadth thins into the Fed window', 'Live now — semis leadership, the equal-weight gap, and how desks are hedging September.', '2026-08-03T13:30:00Z', NULL, '14.2K WATCHING', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), true, ARRAY['NVDA','AVGO','BREADTH']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-opening-bell'), 'semis-earnings-scorecard-guidance-versus-the-multiple', 'EP 1,411', 'Semis earnings scorecard: guidance versus the multiple', 'Which prints justified the re-rating, and where the buy side is quietly trimming.', '2026-08-01T13:30:00Z', 3862, '212K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), false, ARRAY['EARNINGS','SEMIS']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-opening-bell'), 'retail-margins-and-the-quiet-consumer-downgrade', 'EP 1,410', 'Retail margins and the quiet consumer downgrade', 'Three quarters of mix shift in one chart, and what it means for discretionary.', '2026-07-31T13:30:00Z', 3071, '168K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), false, ARRAY['RETAIL','MACRO']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-opening-bell'), 'the-2s10s-wants-to-steepen-who-gets-hurt-first', 'EP 1,409', 'The 2s10s wants to steepen — who gets hurt first', 'Positioning that has been offside since June, walked through step by step.', '2026-07-30T13:30:00Z', 3424, '141K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), false, ARRAY['RATES','CURVE']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-opening-bell'), 'when-liquidity-thins-trading-the-last-hour-in-august', 'EP 1,408', 'When liquidity thins: trading the last hour in August', 'Volume profiles, close auctions, and why size behaves differently after 15:30.', '2026-07-29T13:30:00Z', 2978, '133K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), false, ARRAY['LIQUIDITY','ES']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-opening-bell'), 'dollar-strength-is-not-one-trade', 'EP 1,407', 'Dollar strength is not one trade', 'Separating the rate differential story from the risk-off bid in DXY.', '2026-07-28T13:30:00Z', 3140, '119K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), false, ARRAY['FX','DXY']::text[], true);
insert into show (slug, name, tagline, blurb, description, schedule_slot, episodes_count, hours_per_week, monthly_views, cover_media_id, sort, published) values ('the-vol-desk', 'The Vol Desk', 'TWICE WEEKLY · TUE / THU 14:00 ET', 'Options structure, sizing and the trades behind the greeks.', 'Structure before conviction. Every segment ends with a live position: strikes, sizing, and the exit written down before it is on.', 'TUE / THU 14:00 ET', 486, '4 hrs', '1.9M', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), 1, true);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='the-vol-desk'), 'RA', 'Renee Ash', 'Host · ex market-maker, CBOE floor', 0);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='the-vol-desk'), 'JT', 'Julian Terrell', 'Vol strategist · dispersion and skew', 1);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-vol-desk'), 'selling-premium-into-the-print-sizing-the-nvda-event', 'EP 486', 'Selling premium into the print: sizing the NVDA event', 'Why the straddle was fair and the wings were not, with the trade we put on.', '2026-08-01T13:30:00Z', 1865, '156K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), false, ARRAY['NVDA','EARNINGS','VEGA']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-vol-desk'), 'iron-condors-in-a-13-handle-vix', 'EP 485', 'Iron condors in a 13-handle VIX', 'What you are actually paid for when the tails are cheap and the body is not.', '2026-07-30T13:30:00Z', 1658, '128K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), false, ARRAY['VIX','CONDOR']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-vol-desk'), 'rolling-losers-is-a-decision-not-a-reflex', 'EP 484', 'Rolling losers is a decision, not a reflex', 'A blunt segment on when a roll is risk management and when it is denial.', '2026-07-28T13:30:00Z', 2052, '174K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), false, ARRAY['RISK','PROCESS']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='the-vol-desk'), 'skew-as-a-positioning-signal', 'EP 483', 'Skew as a positioning signal', 'Reading put skew across index, semis and single names in one screen.', '2026-07-23T13:30:00Z', 1787, '97K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), false, ARRAY['SKEW','INDEX']::text[], true);
insert into show (slug, name, tagline, blurb, description, schedule_slot, episodes_count, hours_per_week, monthly_views, cover_media_id, sort, published) values ('macro-hour', 'Macro Hour', 'DAILY · WEEKDAYS 16:00 ET', 'Rates, FX and the policy calendar, without the theatre.', 'Rates, currencies and central banks in the hour after the close — what the data actually changed, and what was already in the price.', 'WEEKDAYS 16:00 ET', 902, '5 hrs', '2.6M', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), 2, true);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='macro-hour'), 'TB', 'Tomas Bek', 'Host · former rates strategist', 0);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='macro-hour'), 'LH', 'Lena Hoffmann', 'FX contributor · London desk', 1);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='macro-hour'), 'powells-window-three-ways-the-september-dot-plot-lands', 'EP 902', 'Powell''s window: three ways the September dot plot lands', 'Scenario map for the meeting, and the trades that express each one cleanly.', '2026-08-02T13:30:00Z', 2892, '231K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), false, ARRAY['FED','RATES']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='macro-hour'), 'yen-carry-round-three', 'EP 901', 'Yen carry, round three', 'Positioning after the unwind, and where the funding trade is rebuilding.', '2026-07-30T13:30:00Z', 2656, '188K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), false, ARRAY['JPY','CARRY']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='macro-hour'), 'the-inflation-print-nobody-hedged', 'EP 900', 'The inflation print nobody hedged', 'Services stickiness, shelter lags, and why the front end shrugged.', '2026-07-29T13:30:00Z', 2463, '162K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), false, ARRAY['CPI','FRONT END']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='macro-hour'), 'fiscal-supply-is-the-new-duration-risk', 'EP 899', 'Fiscal supply is the new duration risk', 'Auction sizes, dealer balance sheets, and the term premium question.', '2026-07-28T13:30:00Z', 2815, '144K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), false, ARRAY['TREASURIES','SUPPLY']::text[], true);
insert into show (slug, name, tagline, blurb, description, schedule_slot, episodes_count, hours_per_week, monthly_views, cover_media_id, sort, published) values ('chart-session', 'Chart Session', 'DAILY · 12:00 ET', 'Levels, breadth and viewer chart requests, live.', 'Half an hour of levels. Viewers send tickers, we mark them up live — support, breadth, relative strength, and where the trade is invalidated.', 'DAILY 12:00 ET', 1140, '2.5 hrs', '3.1M', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), 3, true);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='chart-session'), 'IG', 'Ilya Grant', 'Host · technician, 20 years on the tape', 0);
insert into host (show_id, initials, name, role, sort) values ((select id from show where slug='chart-session'), 'AR', 'Amara Reid', 'Contributor · breadth and market internals', 1);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='chart-session'), 'where-the-tape-breaks-mapping-5-940-to-6-010', 'EP 1,140', 'Where the tape breaks: mapping 5,940 to 6,010', 'The two levels that decide whether August chops or trends.', '2026-08-01T13:30:00Z', 1367, '142K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), false, ARRAY['ES','LEVELS']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='chart-session'), 'viewer-requests-12-tickers-12-invalidation-points', 'EP 1,139', 'Viewer requests: 12 tickers, 12 invalidation points', 'Fast marks on the most-asked names, each with a line that kills the idea.', '2026-07-31T13:30:00Z', 1579, '121K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), false, ARRAY['REQUESTS','SETUPS']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='chart-session'), 'relative-strength-screens-that-survive-a-chop', 'EP 1,138', 'Relative strength screens that survive a chop', 'Why most RS screens break in range markets, and a version that does not.', '2026-07-30T13:30:00Z', 1192, '108K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), false, ARRAY['RS','SCREENS']::text[], true);
insert into episode (show_id, slug, ep_no, title, description, published_at, duration_sec, views, video_url, thumb_media_id, is_live, tags, published) values ((select id from show where slug='chart-session'), 'reading-order-flow-without-a-level-2-addiction', 'EP 1,137', 'Reading order flow without a level 2 addiction', 'What the book tells you, what it does not, and how to stop over-trading it.', '2026-07-29T13:30:00Z', 1471, '205K VIEWS', NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), false, ARRAY['FLOW','PROCESS']::text[], true);

-- on-demand catalog: categories, subcategories, videos
insert into category (slug, name, blurb, cover_media_id, sort, published) values ('macro-rates', 'Macro & Rates', 'Central banks, the curve, and the data that moves it.', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), 0, true);
insert into category (slug, name, blurb, cover_media_id, sort, published) values ('options-volatility', 'Options & Volatility', 'Structure, sizing and the greeks that actually matter.', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), 1, true);
insert into category (slug, name, blurb, cover_media_id, sort, published) values ('technicals-flow', 'Technicals & Flow', 'Levels, breadth, and reading the book honestly.', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), 2, true);
insert into category (slug, name, blurb, cover_media_id, sort, published) values ('earnings', 'Earnings', 'Prints, guidance, and the multiple that follows.', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), 3, true);
insert into category (slug, name, blurb, cover_media_id, sort, published) values ('interviews-long-form', 'Interviews & Long Form', 'Hours with the people who actually run risk.', (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), 4, true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='macro-rates'), 'macro-rates-fed', 'Fed & policy', 'Meetings, dot plots and the path.', 0);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-fed'), (select id from show where name='Macro Hour' limit 1), 'powells-window-three-ways-the-september-dot-plot-lands-2', 'Powell''s window: three ways the September dot plot lands', NULL, '2026-08-02T13:30:00Z', 2892, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-fed'), (select id from show where name='Macro Hour' limit 1), 'reading-the-statement-not-the-presser', 'Reading the statement, not the presser', NULL, '2026-07-24T13:30:00Z', 2381, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-fed'), (select id from show where name='Macro Hour' limit 1), 'what-a-2026-cut-path-actually-prices', 'What a 2026 cut path actually prices', NULL, '2026-07-17T13:30:00Z', 2642, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='macro-rates'), 'macro-rates-cpi', 'Inflation & the curve', 'Prints, shelter lags, term premium.', 1);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-cpi'), (select id from show where name='Macro Hour' limit 1), 'the-inflation-print-nobody-hedged-2', 'The inflation print nobody hedged', NULL, '2026-07-29T13:30:00Z', 2463, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-cpi'), (select id from show where name='The Opening Bell' limit 1), 'the-2s10s-wants-to-steepen-who-gets-hurt-first-2', 'The 2s10s wants to steepen — who gets hurt first', NULL, '2026-07-30T13:30:00Z', 3424, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-cpi'), (select id from show where name='Macro Hour' limit 1), 'fiscal-supply-is-the-new-duration-risk-2', 'Fiscal supply is the new duration risk', NULL, '2026-07-28T13:30:00Z', 2815, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='macro-rates'), 'macro-rates-fx', 'FX & carry', 'Dollar, yen, and funding trades.', 2);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-fx'), (select id from show where name='Macro Hour' limit 1), 'yen-carry-round-three-2', 'Yen carry, round three', NULL, '2026-07-30T13:30:00Z', 2656, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-fx'), (select id from show where name='The Opening Bell' limit 1), 'dollar-strength-is-not-one-trade-2', 'Dollar strength is not one trade', NULL, '2026-07-28T13:30:00Z', 3140, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='macro-rates-fx'), (select id from show where name='Macro Hour' limit 1), 'cable-into-the-london-fix', 'Cable into the London fix', NULL, '2026-07-21T13:30:00Z', 2129, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='options-volatility'), 'options-volatility-premium', 'Premium selling', 'Getting paid, and what for.', 0);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-premium'), (select id from show where name='The Vol Desk' limit 1), 'selling-premium-into-the-nvda-print-sizing-and-exits', 'Selling premium into the NVDA print — sizing and exits', NULL, '2026-08-01T13:30:00Z', 1865, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-premium'), (select id from show where name='The Vol Desk' limit 1), 'iron-condors-in-a-13-handle-vix-2', 'Iron condors in a 13-handle VIX', NULL, '2026-07-30T13:30:00Z', 1658, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-premium'), (select id from show where name='The Vol Desk' limit 1), 'rolling-losers-is-a-decision-not-a-reflex-2', 'Rolling losers is a decision, not a reflex', NULL, '2026-07-28T13:30:00Z', 2052, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='options-volatility'), 'options-volatility-skew', 'Skew & structure', 'Surface reading across index and single names.', 1);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-skew'), (select id from show where name='The Vol Desk' limit 1), 'skew-as-a-positioning-signal-2', 'Skew as a positioning signal', NULL, '2026-07-23T13:30:00Z', 1787, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-skew'), (select id from show where name='The Vol Desk' limit 1), 'dispersion-the-trade-behind-index-vol', 'Dispersion: the trade behind index vol', NULL, '2026-07-16T13:30:00Z', 2000, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-skew'), (select id from show where name='The Vol Desk' limit 1), 'term-structure-when-the-event-is-priced-twice', 'Term structure when the event is priced twice', NULL, '2026-07-09T13:30:00Z', 1735, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='options-volatility'), 'options-volatility-events', 'Event trades', 'Earnings, prints, and IV crush.', 2);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-events'), (select id from show where name='The Vol Desk' limit 1), 'iv-crush-what-the-straddle-told-you-before-the-print', 'IV crush: what the straddle told you before the print', NULL, '2026-07-25T13:30:00Z', 1574, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-events'), (select id from show where name='The Vol Desk' limit 1), 'sizing-a-binary-half-the-conviction-twice-the-plan', 'Sizing a binary: half the conviction, twice the plan', NULL, '2026-07-11T13:30:00Z', 1838, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='options-volatility-events'), (select id from show where name='Macro Hour' limit 1), 'hedging-a-fed-day-without-paying-for-it-twice', 'Hedging a Fed day without paying for it twice', NULL, '2026-07-03T13:30:00Z', 2232, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='technicals-flow'), 'technicals-flow-levels', 'Levels & breadth', 'Where the tape breaks.', 0);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-levels'), (select id from show where name='Chart Session' limit 1), 'where-the-tape-breaks-mapping-5-940-to-6-010-2', 'Where the tape breaks: mapping 5,940 to 6,010', NULL, '2026-08-01T13:30:00Z', 1367, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-levels'), (select id from show where name='The Opening Bell' limit 1), 'why-the-equal-weight-s-p-tells-a-different-story', 'Why the equal-weight S&P tells a different story', NULL, '2026-07-31T13:30:00Z', 398, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-levels'), (select id from show where name='Chart Session' limit 1), 'relative-strength-screens-that-survive-a-chop-2', 'Relative strength screens that survive a chop', NULL, '2026-07-30T13:30:00Z', 1192, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='technicals-flow'), 'technicals-flow-flow', 'Order flow', 'The book, the auction, the close.', 1);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-flow'), (select id from show where name='Chart Session' limit 1), 'reading-order-flow-without-a-level-2-addiction-2', 'Reading order flow without a level 2 addiction', NULL, '2026-07-29T13:30:00Z', 1471, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-flow'), (select id from show where name='The Opening Bell' limit 1), 'when-liquidity-thins-trading-the-last-hour-in-august-2', 'When liquidity thins: trading the last hour in August', NULL, '2026-07-29T13:30:00Z', 2978, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-flow'), (select id from show where name='Chart Session' limit 1), 'close-auctions-the-five-minutes-that-set-your-fill', 'Close auctions: the five minutes that set your fill', NULL, '2026-07-22T13:30:00Z', 1267, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='technicals-flow'), 'technicals-flow-requests', 'Viewer requests', 'Your tickers, marked up live.', 2);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-requests'), (select id from show where name='Chart Session' limit 1), 'viewer-requests-12-tickers-12-invalidation-points-2', 'Viewer requests: 12 tickers, 12 invalidation points', NULL, '2026-07-31T13:30:00Z', 1579, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-requests'), (select id from show where name='Chart Session' limit 1), 'requests-semis-banks-and-one-very-broken-small-cap', 'Requests: semis, banks and one very broken small cap', NULL, '2026-07-24T13:30:00Z', 1544, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='technicals-flow-requests'), (select id from show where name='Chart Session' limit 1), 'requests-the-three-charts-everyone-asked-for-twice', 'Requests: the three charts everyone asked for twice', NULL, '2026-07-17T13:30:00Z', 1382, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='earnings'), 'earnings-semis', 'Semis & AI', 'The leadership trade, quarter by quarter.', 0);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-semis'), (select id from show where name='The Opening Bell' limit 1), 'semis-earnings-scorecard-guidance-versus-the-multiple-2', 'Semis earnings scorecard: guidance versus the multiple', NULL, '2026-08-01T13:30:00Z', 3862, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-semis'), (select id from show where name='The Opening Bell' limit 1), 'capex-disclosures-are-the-real-guide', 'Capex disclosures are the real guide', NULL, '2026-07-18T13:30:00Z', 3310, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-semis'), (select id from show where name='The Opening Bell' limit 1), 'when-a-beat-is-not-enough', 'When a beat is not enough', NULL, '2026-07-11T13:30:00Z', 3107, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='earnings'), 'earnings-consumer', 'Consumer & retail', 'Margins, mix and the quiet downgrade.', 1);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-consumer'), (select id from show where name='The Opening Bell' limit 1), 'retail-margins-and-the-quiet-consumer-downgrade-2', 'Retail margins and the quiet consumer downgrade', NULL, '2026-07-31T13:30:00Z', 3071, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-consumer'), (select id from show where name='The Opening Bell' limit 1), 'discount-mix-three-quarters-in-one-chart', 'Discount mix: three quarters in one chart', NULL, '2026-07-15T13:30:00Z', 2606, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-consumer'), (select id from show where name='The Opening Bell' limit 1), 'traffic-versus-ticket-reading-the-same-print-twice', 'Traffic versus ticket: reading the same print twice', NULL, '2026-07-08T13:30:00Z', 2823, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='earnings'), 'earnings-financials', 'Financials', 'NII, credit, and the deposit question.', 2);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-financials'), (select id from show where name='Macro Hour' limit 1), 'net-interest-income-when-the-curve-steepens', 'Net interest income when the curve steepens', NULL, '2026-07-26T13:30:00Z', 2538, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-financials'), (select id from show where name='The Opening Bell' limit 1), 'credit-normalization-or-credit-crack', 'Credit normalization or credit crack', NULL, '2026-07-19T13:30:00Z', 2916, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='earnings-financials'), (select id from show where name='The Opening Bell' limit 1), 'regionals-the-deposit-beta-nobody-modelled', 'Regionals: the deposit beta nobody modelled', NULL, '2026-07-12T13:30:00Z', 2755, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='interviews-long-form'), 'interviews-long-form-desk', 'The desk', 'Traders on their worst and best books.', 0);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-desk'), (select id from show where name='The Long Position' limit 1), 'a-prop-desk-head-on-risk-limits-hiring-and-blowups', 'A prop desk head on risk limits, hiring and blowups', NULL, '2026-07-30T13:30:00Z', 3520, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-desk'), (select id from show where name='The Long Position' limit 1), 'the-trade-that-broke-a-40m-book', 'The trade that broke a $40m book', NULL, '2026-07-23T13:30:00Z', 4323, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-desk'), (select id from show where name='The Long Position' limit 1), 'twenty-years-of-futures-what-changed-what-never-does', 'Twenty years of futures: what changed, what never does', NULL, '2026-07-16T13:30:00Z', 4101, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='interviews-long-form'), 'interviews-long-form-process', 'Careers & process', 'Drawdowns, journals, and staying in the seat.', 1);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-process'), (select id from show where name='The Long Position' limit 1), 'what-a-15-drawdown-does-to-your-process', 'What a 15% drawdown does to your process', NULL, '2026-07-09T13:30:00Z', 2479, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-process'), (select id from show where name='Chart Session' limit 1), 'stop-hunting-is-not-a-strategy', 'Stop hunting is not a strategy', NULL, '2026-07-27T13:30:00Z', 2815, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-process'), (select id from show where name='The Long Position' limit 1), 'journaling-for-people-who-hate-journaling', 'Journaling for people who hate journaling', NULL, '2026-07-02T13:30:00Z', 2327, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '{}'::text[], true);
insert into subcategory (category_id, slug, name, blurb, sort) values ((select id from category where slug='interviews-long-form'), 'interviews-long-form-funds', 'Funds & founders', 'Allocators, PMs and the business of trading.', 2);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-funds'), (select id from show where name='The Long Position' limit 1), 'raising-a-first-fund-in-a-flat-year', 'Raising a first fund in a flat year', NULL, '2026-06-25T13:30:00Z', 3734, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-funds'), (select id from show where name='The Long Position' limit 1), 'an-allocator-on-what-actually-gets-funded', 'An allocator on what actually gets funded', NULL, '2026-06-18T13:30:00Z', 3389, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '{}'::text[], true);
insert into video (subcategory_id, show_id, slug, title, description, published_at, duration_sec, views, video_url, thumb_media_id, tags, published) values ((select id from subcategory where slug='interviews-long-form-funds'), (select id from show where name='Digital Assets' limit 1), 'basis-trade-mechanics-after-the-etf-flows-normalized', 'Basis trade mechanics after the ETF flows normalized', NULL, '2026-07-28T13:30:00Z', 2184, NULL, NULL, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '{}'::text[], true);

-- authors
insert into author (name) values ('Tomas Bek');
insert into author (name) values ('Renee Ash');
insert into author (name) values ('Ilya Grant');
insert into author (name) values ('Dana Whitfield');
insert into author (name) values ('Amara Reid');
insert into author (name) values ('Lena Hoffmann');
insert into author (name) values ('Marcus Oyelaran');

-- articles
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('the-feds-last-mile-is-a-positioning-problem-not-a-data-problem', (select id from category where name='Macro & Rates' limit 1), (select id from author where name='Tomas Bek' limit 1), 'The Fed''s last mile is a positioning problem, not a data problem', 'Everyone agrees on the direction. Almost nobody agrees on the size — and that is where the pain trade lives.', $j$["The September meeting is the first in two years where the front end and the strategist consensus disagree by more than a single cut. That gap is not an information problem — the data is public and unusually clean. It is a positioning problem: the market has been paid to fade extremes since March, and fading extremes is now the crowded trade.","What matters for the next four weeks is less the print and more who has to move if the print is boring. Real money has duration on, fast money is short the front end, and both are sized as if the distribution is narrow. It is not.","Our read: own optionality around the meeting rather than a directional view. The cheapest expression is still in the curve, not in outright levels."]$j$::jsonb, 6, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '2026-08-03T13:30:00Z', true, true);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('a-13-handle-vix-does-not-mean-the-tails-are-cheap', (select id from category where name='Options & Volatility' limit 1), (select id from author where name='Renee Ash' limit 1), 'A 13-handle VIX does not mean the tails are cheap', 'Index vol is low because dispersion is high. Those are different trades and they are being priced as one.', $j$["Single-name implied vol has barely moved while index vol has bled for six weeks. That is textbook dispersion, and it is what makes the headline VIX number misleading for anyone selling premium on the index.","If you are short index vol here, you are short correlation, whether or not you meant to be. The position works until one sector stops moving independently — and semis are the obvious candidate.","Sizing rule we keep repeating on the show: half the notional you think the edge deserves, and write the exit down before the position is on."]$j$::jsonb, 5, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_wo6oltwo6oltwo6o.png' limit 1), '2026-08-02T13:30:00Z', true, false);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('breadth-has-been-telling-a-different-story-since-june', (select id from category where name='Technicals & Flow' limit 1), (select id from author where name='Ilya Grant' limit 1), 'Breadth has been telling a different story since June', 'The index is up. The median stock is not. Here is the level that decides which one is right.', $j$["Equal-weight has underperformed cap-weight for nine of the last eleven weeks. That is not automatically bearish — narrow tapes can run for months — but it does change what a break of 5,940 means.","Watch participation on any move above 6,010. If fewer than half the S&P names confirm, the breakout is a leadership event, not a market event, and it should be traded through the leaders rather than the index."]$j$::jsonb, 4, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_mlj41hmlj41hmlj4.png' limit 1), '2026-08-01T13:30:00Z', true, false);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('capex-disclosures-are-the-only-guidance-that-matters-this-quarter', (select id from category where name='Earnings' limit 1), (select id from author where name='Dana Whitfield' limit 1), 'Capex disclosures are the only guidance that matters this quarter', 'Forget the beat. The spend schedule is where the multiple gets decided.', $j$["Three of the four largest hyperscalers moved their capex language this quarter without moving the headline number. The buy side noticed; the tape took two sessions to.","For semis, the read-through is mechanical: capex commitments dated beyond eighteen months are being valued at roughly half the multiple of near-term orders. That spread is the trade.","The risk is that a single guidance walk-back re-rates the whole complex. Position accordingly — this is a group where the correlation goes to one on bad news."]$j$::jsonb, 7, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm-fa91b74f.png' limit 1), '2026-07-31T13:30:00Z', true, false);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('the-book-that-broke-me-was-the-one-i-understood-best', (select id from category where name='Interviews & Long Form' limit 1), (select id from author where name='Amara Reid' limit 1), '“The book that broke me was the one I understood best”', 'A prop desk head on risk limits, hiring, and the drawdown that changed how he sizes everything.', $j$["He has run the same desk for eleven years and has fired more traders for process than for P&L. The conversation kept returning to one idea: conviction is not a risk input.","On hiring: he no longer asks candidates for their best trade. He asks for the trade they held too long, and listens for whether the story has a number in it."]$j$::jsonb, 12, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0-ef37c215.png' limit 1), '2026-07-30T13:30:00Z', true, false);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('yen-carry-is-rebuilding-quietly', (select id from category where name='Macro & Rates' limit 1), (select id from author where name='Lena Hoffmann' limit 1), 'Yen carry is rebuilding, quietly', 'The unwind is over. The funding trade is back on — with worse liquidity underneath it.', $j$["Positioning data suggests the carry trade has rebuilt roughly two thirds of what came off in the spring, but through a narrower set of counterparties.","That matters more than the size. The same notional in fewer hands means the next unwind is faster, and the gaps are wider. Hedge the gap, not the level."]$j$::jsonb, 5, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_bsfmq5bsfmq5bsfm.png' limit 1), '2026-07-29T13:30:00Z', true, false);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('the-last-hour-in-august-is-a-different-market', (select id from category where name='Technicals & Flow' limit 1), (select id from author where name='Ilya Grant' limit 1), 'The last hour in August is a different market', 'Thin books, heavier closes, and fills that do not look like your backtest.', $j$["Close auction share of daily volume has climbed for four straight Augusts. If your strategy assumes continuous liquidity, August is where the assumption quietly stops being true.","Practical fix: move execution earlier, size down into the final thirty minutes, and treat the auction print as information rather than a target."]$j$::jsonb, 4, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_jik0zpjik0zpjik0.png' limit 1), '2026-07-28T13:30:00Z', true, false);
insert into article (slug, category_id, author_id, title, dek, body, read_minutes, hero_media_id, published_at, published, featured) values ('retails-downgrade-is-happening-in-the-mix-not-the-top-line', (select id from category where name='Earnings' limit 1), (select id from author where name='Marcus Oyelaran' limit 1), 'Retail''s downgrade is happening in the mix, not the top line', 'Traffic is fine. Ticket is fine. What people put in the basket is not.', $j$["Three consecutive quarters of mix shift toward private label and smaller pack sizes is not a promotion cycle. It is a consumer decision that shows up in margin before it shows up in revenue.","The names that have already guided margin down are, counterintuitively, the cleaner longs here. The risk sits with anyone still holding a full-year margin number set in January."]$j$::jsonb, 6, (select id from media_asset where url = 'uploads/Gemini_Generated_Image_udj4nuudj4nuudj4.png' limit 1), '2026-07-27T13:30:00Z', true, false);

-- schedule
insert into schedule_slot (day_of_week, time_et, show_id, hosts_label, is_live, sort) values (NULL, '09:30', (select id from show where name='The Opening Bell' limit 1), 'Whitfield · Oyelaran', true, 0);
insert into schedule_slot (day_of_week, time_et, show_id, hosts_label, is_live, sort) values (NULL, '12:00', (select id from show where name='Chart Session' limit 1), 'Ilya Grant', false, 1);
insert into schedule_slot (day_of_week, time_et, show_id, hosts_label, is_live, sort) values (NULL, '14:00', (select id from show where name='The Vol Desk' limit 1), 'Renee Ash', false, 2);
insert into schedule_slot (day_of_week, time_et, show_id, hosts_label, is_live, sort) values (NULL, '16:00', (select id from show where name='Macro Hour' limit 1), 'Tomas Bek', false, 3);
insert into schedule_slot (day_of_week, time_et, show_id, hosts_label, is_live, sort) values (NULL, '18:30', (select id from show where name='The Long Position' limit 1), 'Amara Reid', false, 4);
insert into schedule_slot (day_of_week, time_et, show_id, hosts_label, is_live, sort) values (NULL, '20:00', (select id from show where name='Asia Handover' limit 1), 'Singapore desk', false, 5);

-- ticker quotes (mock)
insert into ticker_quote (symbol, price, change, direction, sort) values ('ES', '5,942.25', '+0.41%', 'up', 0);
insert into ticker_quote (symbol, price, change, direction, sort) values ('NQ', '21,488.50', '+0.78%', 'up', 1);
insert into ticker_quote (symbol, price, change, direction, sort) values ('SPY', '591.14', '+0.38%', 'up', 2);
insert into ticker_quote (symbol, price, change, direction, sort) values ('NVDA', '184.62', '+2.14%', 'up', 3);
insert into ticker_quote (symbol, price, change, direction, sort) values ('AAPL', '228.05', '-0.32%', 'down', 4);
insert into ticker_quote (symbol, price, change, direction, sort) values ('TSLA', '341.77', '-1.08%', 'down', 5);
insert into ticker_quote (symbol, price, change, direction, sort) values ('VIX', '14.82', '-3.40%', 'down', 6);
insert into ticker_quote (symbol, price, change, direction, sort) values ('US10Y', '4.216%', '+2 bp', 'up', 7);
insert into ticker_quote (symbol, price, change, direction, sort) values ('DXY', '103.41', '-0.12%', 'down', 8);
insert into ticker_quote (symbol, price, change, direction, sort) values ('CL', '68.94', '+1.62%', 'up', 9);
insert into ticker_quote (symbol, price, change, direction, sort) values ('GC', '3,412.60', '+0.27%', 'up', 10);
insert into ticker_quote (symbol, price, change, direction, sort) values ('BTC', '112,480', '-0.94%', 'down', 11);
insert into ticker_quote (symbol, price, change, direction, sort) values ('EURUSD', '1.0862', '+0.15%', 'up', 12);
insert into ticker_quote (symbol, price, change, direction, sort) values ('AVGO', '1,742.10', '+3.02%', 'up', 13);

-- chat messages (mock seed)
insert into chat_message (display_name, text, kind, sort) values ('flowtrader_kc', 'breadth is the whole story today, equal weight is red', 'user', 0);
insert into chat_message (display_name, text, kind, sort) values ('vega_hunter', 'IV crush after the print was brutal on my calls', 'user', 1);
insert into chat_message (display_name, text, kind, sort) values ('MOD · Priya', 'Reminder: chart requests go in the Q&A tab.', 'mod', 2);
insert into chat_message (display_name, text, kind, sort) values ('tape_reader88', 'NVDA holding VWAP all session, buyers still there', 'user', 3);
insert into chat_message (display_name, text, kind, sort) values ('sarah_m', 'any read on the 2s10s here?', 'user', 4);
insert into chat_message (display_name, text, kind, sort) values ('desk_of_one', 'watching 5,940 as the line in the sand', 'user', 5);
insert into chat_message (display_name, text, kind, sort) values ('quietbid', 'this segment on order flow is the best one all week', 'user', 6);
insert into chat_message (display_name, text, kind, sort) values ('hedgehog_ldn', 'cable looks heavy into the London fix', 'user', 7);
insert into chat_message (display_name, text, kind, sort) values ('MOD · Priya', 'Dana takes viewer questions at the bottom of the hour.', 'mod', 8);
insert into chat_message (display_name, text, kind, sort) values ('swingsonly', 'added to semis on that flush, small size', 'user', 9);

-- home layout blocks (derived from newest content)
insert into home_block (type, ref_type, ref_id, sort)
  select 'featured', 'episode', e.id, (row_number() over (order by e.published_at desc nulls last))::int
  from episode e order by e.published_at desc nulls last limit 6;
insert into home_block (type, ref_type, ref_id, sort)
  select 'most_watched', 'episode', e.id, (row_number() over (order by e.published_at desc nulls last))::int
  from episode e order by e.published_at desc nulls last offset 6 limit 5;
insert into home_block (type, ref_type, ref_id, sort)
  select 'up_next', 'video', v.id, (row_number() over (order by v.published_at desc nulls last))::int
  from video v order by v.published_at desc nulls last limit 3;

-- dev admin (email admin@tape.local / password 'password' — CHANGE in real envs)
insert into admin_user (email, password_hash, role, active) values ('admin@tape.local', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN', true);
